export const Type = {
  FETCH_CONTACTS_REQUEST: "FETCH_CONTACTS_REQUEST",
  FETCH_CONTACTS_SUCCESS: "FETCH_CONTACTS_SUCCESS",
  FETCH_CONTACTS_ERROR: "FETCH_CONTACTS_ERROR",
  //-----
  ADD_CONTACT_REQUEST: "ADD_CONTACT_REQUEST",
  ADD_CONTACT_SUCCESS: "ADD_CONTACT_SUCCESS",
  ADD_CONTACT_ERROR: "ADD_CONTACT_ERROR",
  //-----
  DELETE_CONTACT_REQUEST: "DELETE_CONTACT_REQUEST",
  DELETE_CONTACT_SUCCESS: "DELETE_CONTACT_SUCCESS",
  DELETE_CONTACT_ERROR: "DELETE_CONTACT_ERROR",
  //-----
  FILTER_CONTACTS: "FILTER_CONTACTS",
  //-----
  ADD_CONTACT: "ADD_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT",
  GET_CONTACTS_FROM_LOCAL_STORAGE: "GET_CONTACTS_FROM_LOCAL_STORE",
};
